name: documentation-website MARKDOWN-LINT
on:
  workflow_run:
    types:
      - completed
    workflows:
      - NPM Caches
    paths:
    - 'documentation-website/*.md'
    - 'documentation-website/package-lock.json'
    - '.github/workflows/documentation-website.mdlint.yml'
env:
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.CURRENT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.CURRENT_NODE_VERSION }}
      - name: Restore Builds
        id: cache-builds-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/.npm
          key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
      - run: cd documentation-website && npm ci
      - run: cd documentation-website && npm run lint-md
