name: Spellcheck
on:
  workflow_run:
    types:
      - completed
    workflows:
      - NPM Cache
    paths:
    - '**.md'
    - 'package-lock.json'
    - '.github/workflows/spellcheck.yml'
env:
  CURRENT_NODE_VERSION: ${{ vars.CURRENT_NODE_VERSION || 'latest' }}
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Node.js environment ${{ env.CURRENT_NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.CURRENT_NODE_VERSION }}
    - name: Wait for cache to be built
      uses: lewagon/wait-on-check-action@v1.3.4
      with:
        ref: ${{ github.ref }}
        check-name: 'Build full npm cache'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10
    - name: Restore Builds
      id: cache-builds-restore
      uses: actions/cache/restore@v4
      with:
        path: ~/.npm
        key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
    - name: Build root
      run: npm ci
    - name: spellcheck
      run: npm run spellcheck
